use base64::Engine;
use regex::Regex;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

fn compute_hash(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    let hash = hasher.finalize();
    base64::engine::general_purpose::STANDARD.encode(hash)
}

fn main() {
    println!("cargo:rerun-if-changed=src/templates/");

    let templates_dir = Path::new("src/templates");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("csp_hashes.rs");

    let mut script_hashes = Vec::new();
    let mut style_hashes = Vec::new();

    let script_re = Regex::new(r"(?s)<script>(.*?)</script>").unwrap();
    let style_re = Regex::new(r"(?s)<style>(.*?)</style>").unwrap();

    for entry in fs::read_dir(templates_dir).expect("Failed to read templates directory") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();

        if path.extension().map_or(false, |ext| ext == "html") {
            let content = fs::read_to_string(&path).expect("Failed to read template file");
            let filename = path.file_stem().unwrap().to_str().unwrap();
            let prefix = filename.to_uppercase().replace('-', "_");

            for (i, cap) in script_re.captures_iter(&content).enumerate() {
                let hash_b64 = compute_hash(&cap[1]);
                let const_name = format!("{}_SCRIPT_{}_HASH", prefix, i);
                script_hashes.push((const_name, hash_b64));
            }

            for (i, cap) in style_re.captures_iter(&content).enumerate() {
                let hash_b64 = compute_hash(&cap[1]);
                let const_name = format!("{}_STYLE_{}_HASH", prefix, i);
                style_hashes.push((const_name, hash_b64));
            }
        }
    }

    let mut output = String::from("// Auto-generated by build.rs - do not edit manually\n\n");

    for (name, hash) in &script_hashes {
        output.push_str(&format!(
            "pub const {}: &str = \"'sha256-{}'\";\n",
            name, hash
        ));
    }

    for (name, hash) in &style_hashes {
        output.push_str(&format!(
            "pub const {}: &str = \"'sha256-{}'\";\n",
            name, hash
        ));
    }

    output.push_str("\n/// Combined script-src value for CSP header\n");
    output.push_str("pub fn script_src_hashes() -> String {\n");
    output.push_str("    [\n");
    for (name, _) in &script_hashes {
        output.push_str(&format!("        {},\n", name));
    }
    output.push_str("    ].join(\" \")\n");
    output.push_str("}\n");

    output.push_str("\n/// Combined style-src value for CSP header\n");
    output.push_str("pub fn style_src_hashes() -> String {\n");
    output.push_str("    [\n");
    for (name, _) in &style_hashes {
        output.push_str(&format!("        {},\n", name));
    }
    output.push_str("    ].join(\" \")\n");
    output.push_str("}\n");

    fs::write(&dest_path, output).expect("Failed to write CSP hashes file");
}
