use base64::Engine;
use regex::Regex;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/templates/");

    let templates_dir = Path::new("src/templates");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("csp_hashes.rs");

    let mut hashes = Vec::new();

    // Process each HTML template
    for entry in fs::read_dir(templates_dir).expect("Failed to read templates directory") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();

        if path.extension().map_or(false, |ext| ext == "html") {
            let content = fs::read_to_string(&path).expect("Failed to read template file");
            let filename = path.file_stem().unwrap().to_str().unwrap();

            // Extract all script blocks and compute hashes
            let script_re = Regex::new(r"(?s)<script>(.*?)</script>").unwrap();
            for (i, cap) in script_re.captures_iter(&content).enumerate() {
                let script_content = &cap[1];

                // Compute SHA-256 hash
                let mut hasher = Sha256::new();
                hasher.update(script_content.as_bytes());
                let hash = hasher.finalize();

                // Base64 encode
                let hash_b64 = base64::engine::general_purpose::STANDARD.encode(hash);

                // Generate constant name: e.g., MIRROR_SCRIPT_0_HASH
                let const_name = format!(
                    "{}_SCRIPT_{}_HASH",
                    filename.to_uppercase().replace('-', "_"),
                    i
                );

                hashes.push((const_name, hash_b64));
            }
        }
    }

    // Generate the Rust file with hash constants
    let mut output = String::from("// Auto-generated by build.rs - do not edit manually\n\n");

    for (name, hash) in &hashes {
        output.push_str(&format!(
            "pub const {}: &str = \"'sha256-{}'\";\n",
            name, hash
        ));
    }

    // Generate a combined CSP script-src value
    output.push_str("\n/// Combined script-src value for CSP header\n");
    output.push_str("pub fn script_src_hashes() -> String {\n");
    output.push_str("    [\n");
    for (name, _) in &hashes {
        output.push_str(&format!("        {},\n", name));
    }
    output.push_str("    ].join(\" \")\n");
    output.push_str("}\n");

    fs::write(&dest_path, output).expect("Failed to write CSP hashes file");
}
